### ISSUE TITLE
interpolate_skipped_contours function

### ISSUE THREAD

**Issue by berzinastella** [lexi-jones/RCLVatlas#2]
Hi,
As I said, I've been having issues with the interpolate_skipped_contours function because it always raises this error
`IndexError: range object index out of range
` 
in the mainfunctions_for_RCLV_atlas.py in line 350 (also 351 then) which are 

```
# Get location of center particle back 2 time steps (~16 days) or 3 time steps (~24 days)
back_ntimesteps_center_lon = float(particle_lon[particle_num,int(24/sim_params['output_freq'])*days_btwn_ntimesteps])
back_ntimesteps_center_lat = float(particle_lat[particle_num,int(24/sim_params['output_freq'])*days_btwn_ntimesteps])
```

I think I have figured out the issue but I am wondering if I'm understanding the function correctly. 
I think that the issue is that  `particle_lon` in the function is read in only for 1 trajectory period (8 days), so `particle_lon` has only 32 time steps (because 6h output). I'm pretty sure that the location selection (be it lon or lat) in `particle_lon[particle_num,int(24/sim_params['output_freq'])*days_btwn_ntimesteps]` gives a higher timestep than 32 because in theory it should look 2 or 3 time steps ahead (therefore 64 or 96 time steps), but the `particle_lon` has only the initial 32 time steps, therefore it raises a range error. I hope you can follow this.

Am I understanding this correctly? If so, shouldn't we somehow concatenate the trajectory files? 
One point that might ot might not be important- you have written the code for .nc parcels soutput which is no longer happening, only .zarr is outputted from parcels. 

I hope you understand my confusion.

Best,
Stella

**Comment by lexi-jones** [comment]
Hi Stella,

I think the misunderstanding is that my trajectories (or "trajectory period" as you call it) were for 32 days backward-in-time total (not 8 days), so I did not need to concatenate trajectory files. Each trajectory file "overlapped" by 8 days. So each trajectory file was something like this, starting at day "0", then going backward-in-time:
Day 0 -> Day -32 
Day -24 -> Day -56
Day -48 -> Day -80
... Etc.

The interpolate_skipped_contours() function was used for some fringe cases described in Section 2.4.3 "Disappearing RCLVs" of the ESSD paper (doi.org/10.5194/essd-16-1475-2024). I'm backtracking the particle set to day 24, or 16 if necessary until I can link the RCLV back up with the previous simulation. 

I've also been meaning to upload a conda environment YML file, and will do that soon so that you can use the same Parcels version that I did with netCDF output, if you'd like. 

I know this is pretty confusing, but hope this is helpful and let me know if you have any other questions.

Best,
Lexi
